os: linux
arch: ppc64le
jobs:
  include:
    - script: date
    - script: date
    - script: date
    - script: date
    - script: date
    - script: date
    - script: date
    - script: date
    - script: date
    - script: date
      
      
