dist: xenial

install:
  - tmux -V

script:
  - wget -O speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
  - chmod +x speedtest-cli
  - python speedtest-cli --single