os: linux
arch: 
  - arm64
  - amd64
script:
  - echo "AAAA"
  - ssh-keygen -R github.com || true >/dev/null 2>&1
  - echo "BBB"
  - ssh-keygen -R github.com >/dev/null 2>&1 || true
  - cat ~/.ssh/known_hosts
  - git clone git@github.com:r-arek/test-queue.git
