language: go
os: linux
group: edge

dist: focal # default (xenial) does not work
arch: pc64le

go:
- 1.18

script:
- ruby -v

deploy:
  provider: releases
  api_key: "asdasdasdas"
  file: /tmp/archive.zip
  skip_cleanup: true
  on:
    tags: true
