language: python

cache:
  directories:
    - ~/.cache/pip

env:
  global:
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels

python:
  - "3.4"

install:
  - pip wheel -r requirements.txt
  - pip install -r requirements.txt

script: true
