os: linux

script:
  - wget https://github.com/mwittenbols/How-to-deploy-a-static-website-to-Elastic-BeanStalk-for-the-Enterprise/blob/master/1InitialDeploymentPackage.zip
addons:
  deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: "$ACCESSKEYID"
    secret_access_key: "$AWS_SECRET_KEY"
    region: ap-northeast-1
    bucket: elasticbeanstalk-ap-northeast-1-529673077012
    app: travis-test
    env: travis-test
    zip_file: 1InitialDeploymentPackage.zip 
