dist: bionic
#jdk: oracle17
arch: amd64
script:
 - curl -s "https://get.sdkman.io?rcupdate=false" | bash
 - source "$HOME/.sdkman/bin/sdkman-init.sh"
 - sdk install java 17.0.2-tem
 - java -version
 - whereis java
 - echo $JAVA_HOME
 - echo $PATH
notifications:
  email: false

