os: linux
php: '7.4'
language: php
dist: xenial
services:
  - redis
  - mysql
script:
  - echo 1
  - wget https://github.com/mwittenbols/How-to-deploy-a-static-website-to-Elastic-BeanStalk-for-the-Enterprise/blob/master/1InitialDeploymentPackage.zip
install:
  - echo 2
before_script:
  - mysql -e "create database dbtest CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
  - composer self-update --rollback
  - composer install
  - export ELASTIC_BEANSTALK_LABEL=travis-voya-${TRAVIS_BRANCH}-$(git rev-parse --verify
    HEAD --short)-$(date +%s)
env:
  - APP_DEBUG='true'
  - DB_CONNECTION='mysql'
  - DB_HOST='127.0.0.1
  - DB_PORT='3306'
  - DB_DATABASE='dbtest'
  - DB_USERNAME='root'
  - DB_PASSWORD=''
  - BROADCAST_DRIVER='log'
  - CACHE_DRIVER='file'
  - REDIS_HOST='127.0.0.1'
  - REDIS_PASSWORD='null'
  - REDIS_PORT='6379'
addons:
  deploy:
  - provider: elasticbeanstalk
    skip_cleanup: true
    access_key_id: "$ACCESSKEYID"
    secret_access_key: "$AWS_SECRET_KEY"
    region: ap-northeast-1
    bucket: elasticbeanstalk-ap-northeast-1-341288657826
    app: travis-test
    env: Travistest-env
    zip_file: 1InitialDeploymentPackage.zip 
