os: linux
arch: ppc64le
jobs:
  include:
    - stage: test
      script: date
      script: date
      script: date
      script: date
      script: date
      script: date
      script: date
      script: date
      script: date
      script: date
      
      
